[package]
name = "bevy-test"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.11.0", features = [ "jpeg" ] }
once_cell = "1.18.0"
variantly = "0.2"
